name: Gauge QA Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./automation
        run: npm install

      - name: Install Gauge
        run: |
          npm install -g @getgauge/cli
          gauge install js

      - name: Run Smoke Tests
        working-directory: ./automation
        run: gauge run specs --tags smoke

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: smoke-report
          path: reports
